<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Manage_OrderofEvents.aspx.cs" Inherits="sckreg.Manage_OrderofEvents" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Manager - Order of Events for Meets</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <h1>Manager - Order of Events for <asp:Label ID="lblMeet" runat="server" Text="<Meet Name - lblmeet>"></asp:Label></h1>
    </div>
    <div>
    <h2>Edit Meet Events Here:</h2>
        <p>
            <asp:GridView ID="gvEvents" runat="server" AllowSorting="True" 
                AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
                AutoGenerateEditButton="True" BackColor="White" BorderColor="#DEDFDE" 
                BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="EventsId" 
                DataSourceID="sqlDS_Events" EmptyDataText="No Events found" ForeColor="Black" 
                GridLines="Vertical">
                <RowStyle BackColor="#F7F7DE" />
                <Columns>
                    <asp:TemplateField HeaderText="EventsId" SortExpression="EventsId">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("EventsId") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label1" runat="server" Text='<%# Bind("EventsId") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="meetId" SortExpression="meetId">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("meetId") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label2" runat="server" Text='<%# Bind("meetId") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="number" SortExpression="number">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("number") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label3" runat="server" Text='<%# Bind("number") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="name" SortExpression="name">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("name") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label4" runat="server" Text='<%# Bind("name") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="competitionId" SortExpression="competitionId">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox5" runat="server" Text='<%# Bind("competitionId") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label5" runat="server" Text='<%# Bind("competitionId") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="levelId" SortExpression="levelId">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox6" runat="server" Text='<%# Bind("levelId") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label6" runat="server" Text='<%# Bind("levelId") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="genderId" SortExpression="genderId">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox7" runat="server" Text='<%# Bind("genderId") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label7" runat="server" Text='<%# Bind("genderId") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="eventOrder" SortExpression="eventOrder">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox8" runat="server" Text='<%# Bind("eventOrder") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label8" runat="server" Text='<%# Bind("eventOrder") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <FooterStyle BackColor="#CCCC99" />
                <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                <AlternatingRowStyle BackColor="White" />
            </asp:GridView>
        </p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
    
    
    </div>
    <div>
    
    
        <asp:SqlDataSource ID="sqlDS_Events" runat="server" 
            ConnectionString="<%$ ConnectionStrings:SCKCLUBConnectionString %>" 
            SelectCommand="SELECT [EventsId], [meetId], [number], [name], [competitionId], [levelId], [genderId], [eventOrder] FROM [tEvents] WHERE ([meetId] = @meetId) ORDER BY left(EventsId,2), [eventOrder]" 
            
            UpdateCommand="UPDATE tEvents SET meetId = @meetId, number = @number, name = @name, competitionId = @competitionId, levelId = @levelId, genderId = @genderId, areaId = @areaId WHERE (EventsId = @EventsId)">
            <SelectParameters>
                <asp:QueryStringParameter DefaultValue="LPI14" Name="meetId" 
                    QueryStringField="qmeet" Type="String" />
            </SelectParameters>
            <UpdateParameters>
                <asp:Parameter Name="meetId" />
                <asp:Parameter Name="number" />
                <asp:Parameter Name="name" />
                <asp:Parameter Name="competitionId" />
                <asp:Parameter Name="levelId" />
                <asp:Parameter Name="genderId" />
                <asp:Parameter Name="areaId" />
                <asp:Parameter Name="EventsId" />
            </UpdateParameters>
        </asp:SqlDataSource>
    
    
    </div>
    </form>
</body>
</html>
